# Code Generated by Sidekick is for learning and experimentation purposes only.
output "dev_file" {
  value = module.artifact_dev.file_path
}

output "prod_file" {
  value = module.artifact_prod.file_path
}
